"""Inception

Revision ID: b9c162bef513
Revises: 
Create Date: 2024-06-17 23:11:39.170826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c162bef513'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('fullname')
    )
    op.create_table('clients',
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('father_name', sa.String(), nullable=False),
    sa.Column('b_day', sa.Date(), nullable=False),
    sa.Column('inn', sa.Integer(), nullable=False),
    sa.Column('supervisor', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('unprocessing', 'processing', 'denied', 'closed', name='statusenum'), nullable=True),
    sa.ForeignKeyConstraint(['supervisor'], ['user.fullname'], ),
    sa.PrimaryKeyConstraint('inn')
    )
    op.create_index(op.f('ix_clients_inn'), 'clients', ['inn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_inn'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('user')
    # ### end Alembic commands ###
